<?php
include 'db.php';
//use Razorpay\Api\Api;
//include 'Razorpay/Razorpay.php';
//$api = new Api('rzp_live_zCL17KOiXbLpHW', 't5Hkm1HC7O9mgPPOLtfzPF4l');

//$payment = $api->payment->fetch('pay_GZ4bfaSFFnvYOP');
//$payment->capture(array('amount' => 1000, 'currency' => 'INR'));

$trans = '9432720e-61d8-4f15-b678-c922c5b75b00';
$sql4 =<<<EOF
    select payment_id from transaction where id = '$trans'
EOF;
$ret4 = pg_query($db, $sql4);

while($row = pg_fetch_row($ret4))
{
  $payid = $row[0];
}
$cmd = "curl -u rzp_live_zCL17KOiXbLpHW:t5Hkm1HC7O9mgPPOLtfzPF4l -X GET https://api.razorpay.com/v1/payments/$payid";
exec($cmd,$result);
$res_val = ($result[0]);
$res_val1 = json_decode ($res_val);
$payamt = $res_val1->amount;

//$cmd1 = "curl -u rzp_live_zCL17KOiXbLpHW:t5Hkm1HC7O9mgPPOLtfzPF4l -H 'content-type: application/json' -X POST https://api.razorpay.com/v1/payments/$pay_id/capture -d '{ "amount": '$payamt', "currency":"INR"}'"
//exec($cmd1,$result);

// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

$ch = curl_init();

$url1 = "https://api.razorpay.com/v1/payments/$payid/capture";
curl_setopt($ch, CURLOPT_URL, $url1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{ \"amount\": $payamt, \"currency\":\"INR\"}");
curl_setopt($ch, CURLOPT_USERPWD, 'rzp_live_zCL17KOiXbLpHW' . ':' . 't5Hkm1HC7O9mgPPOLtfzPF4l');

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo $result;


?>